### PR TITLE
LPS-68512

### PR DESCRIPTION
**Pull request by holatuwol**
Add `JAVA_HOME/bin` to the PATH before starting up Tomcat and Jetty bundles.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@holatuwol what about other appservers? If we don't make sure everyone is doing the same thing, it would be worse to support, right? Since the same code will behave differently on different appservers. At least right now, if we don't do anything, they all fail in the same way.

**Comment by SGM3** [comment]
@shuyangzhou  Would a terminal clause in PortalContextListener be valid?

```
if (PATH not contains JAVA_HOME/bin when JAVA_HOME defined)
    log.error(JAVA_HOME/bin not in PATH)
    // execute proper shutdown sequenece
```

**Comment by shuyangzhou** [comment]
no, that's not right. "PATH not contains JAVA_HOME/bin when JAVA_HOME defined" is ok. We don't require JAVA_HOME at all. As long as we can find a java from PATH, we don't care where that java is from JAVA_HOME/bin or anywhere else.

**Comment by SGM3** [comment]
My question is "PATH not contains JAVA_HOME/bin when JAVA_HOME defined" grounds for shutting down the server, or should this solely be a warning in the log and allow the portal to continue startup? Explicitly, only when JAVA_HOME is defined in either case.

**Comment by shuyangzhou** [comment]
No, this problem is not really related to JAVA_HOME at all. As long as we can find a java on PATH, we don't care where it is from. So the thing you want to assert is there is a java on the PATH. It does not have to be from JAVA_HOME.

**Comment by SGM3** [comment]
```
[myuser@localhost bin]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/myuser/.local/bin:/home/myuser/bin
[myuser@localhost bin]$ echo $JAVA_HOME
/usr/java/jdk1.8.0_102
[myuser@localhost bin]$ readlink -f /usr/bin/java
/usr/java/jdk1.8.0_05/bin/java
...
[myuser@localhost ~]$ ps ef | grep java
...
8119 pts/0    Sl     3:57 /usr/java/jdk1.8.0_102/bin/java .......
....
```

Server starts up without any obvious issues.

Even though the Liferay application itself, being spun up by Tomcat is using the JDK 1.8_102, any process spun up by Liferay would fall under the JDK 1.8_05, since it looks for java in PATH. This is a server configuration that may potential go undetected.

Whether is an issue, may be debatable. I feel this is unintended configuration. Should we look into logging this scenario, should we consider this an issue?

**Comment by shuyangzhou** [comment]
It is not an issue, it is supposed to be this way, we allow ProcessExecutor to use jvms that is different from portal running jvm. The only requirement we have is, all jvm must be jdk8 or above.

**Comment by SGM3** [comment]
So I guess if that is the case, I do not see the need to add logging.

Scenario 1, java not in PATH
"java: No such file or directory" error is logged

Scenario 2, java 7 on path before the java 8

"Program exited with exit code: 1" error is logged

@holatuwol Is there any scenario that you feel is required to be covered? Do we proceed with adding sample configurations for the other application servers?

**Comment by holatuwol** [comment]
@shuyangzhou Why would we want to allow ProcessExecutor to use a completely different JVM? What benefit does that give us?

**Comment by shuyangzhou** [comment]
One of many reasons is allowing 64bit jvm portal to run 32bit sub-process to save memory usage.

**Comment by holatuwol** [comment]
@shuyangzhou Using the PATH for a micro-optimization instead of letting a user explicitly configure it inside of Liferay sounds like a hack to me. Would you accept a fix that allowed advanced users to explicitly change it to something else if you don't want to reuse Liferay's Java?

**Comment by SGM3** [comment]
@shuyangzhou @holatuwol 

I vote to close this issue as Won't Fix.

Adding JAVA_HOME/bin to PATH is a standard practice in the installation process for environments with Java.

Adding JAVA_HOME/bin to PATH from our product may cause unintended consequences if the system administrator follows this well defined standard of java being picked off the PATH and things of adding another version of Java on Path intentionally. Picking Java from JAVA_HOME (when JAVA_HOME is available) is not a standard as well defined as adding Java to PATH.

We could still make a product decision to follow this standard, but offer this as a feature and not an bug fix.

If we do decided on following another practice other than that of picking Java off of PATH, then let us create a new ticket defining the criteria for the standard we will follow.

I will close this issue (probably) by EOD Thurday if no further discussion takes place.

**Comment by shuyangzhou** [comment]
I guess the question here is what this is really about?
a) do we have a Java to use for processexecutor?
b) which Java we have for processexecutor?

For a), that is really not a problem, we must have one, we require Java to be on the PATH.

For b), this is something we can talk about. It is technically possible that portal is running on java8, but the Java on PATH is 7 or older, causing processexecutor fail to run. In case like this, we need to make a decision to say whether it is a configuration mistake. I am actually ok with both ways. If we say it is a configuration mistake, still there is nothing we need to do. If we say it is not, we will need to provide a configurable default settings for processexecutor's default Java location, which should still default to Java on PATH, but allowing administrator to change it in case it is necessary.

Is this making sense to you guys?

**Comment by SGM3** [comment]
For B,

The original proposition is to use JAVA_HOME when available vs PATH. 

This is a way to "provide a configurable default settings for processexecutor's default Java location, which should still default to Java on PATH, but allowing administrator to change it in case it is necessary."

When JAVA_HOME is not defined, it would default to PATH.

The argument against this is this would restrict the ProcessExecutor to the runtime for certain application servers that require JAVA_HOME to be set.

I personally feel like this is a better "defaulting" scenario. But as argued before, this does not follow well define standard practices.

The next best thing would be an addition for a portal property that would override a default value of java from PATH specifically for (Local) ProcessExecutioner, this way no other components would be affected when looking for tools in PATH, especially when you Fabric.

**Comment by shuyangzhou** [comment]
JAVA_HOME is never a good choice, it is env variable, worse than PATH, as it is not universal.
When I said configurable, I meant at portal level.

**Comment by SGM3** [comment]
Closing issue LPS-68512

The issue states:
"Liferay requires a JAVA_HOME and PATH variables set. However, Liferay really only needs JAVA_HOME set."

This is taken to be false and therefore not an issue, this will not be fixed.

@shuyangzhou How do we gauge the need for a configurable ProcessExecution javaExecutable property, should we create a new feature ticket?

**Comment by shuyangzhou** [comment]
That goes back to whether "b) which Java we have for processexecutor?" is a real problem.
I can go either way. Do we really want to allow an unsupported java showing on PATH? That also means unsupported jps/jmap/jstack on PATH. And execution to them are not controlled by processexecutor at all. We will need ways to deal with them separately.

So I more lean to say we should not allow it, to keep things simple.

If you can find more reasons to support that we should allow it, I can make it happen. But this will be a very low priority task.

**Comment by holatuwol** [comment]
@SGM3  My main issue is that the error message does not give you any hint at all about what went wrong or how to fix it. I'd like for us to never run into that error message, but if we're going to allow for that error message to happen, I don't mind limiting the fix to simply making the default Tomcat bundle work (previous commit) and adding logging indicating which executable we're running (new commit).

**Comment by shuyangzhou** [comment]
@holatuwol you can not change the processexecutor that way. It is breaking the responsibility separation and the unit tests.

Think it this way, does the jdk thread pool executor tells you what went wrong in your runnable? No, because it is not his business to know that. When it comes to this design, there is a line here. Processexecutor must not try to detect the system itself, it is simply told what to do. Not trying to do everything itself. It is already a very complex class with unusual design, we should not add anything that is not absolutely needed into it.

**Comment by holatuwol** [comment]
@shuyangzhou Again, the problem is that when it errors out, the error messages provide zero hints about what you're supposed to do to resolve the issue.

For the JDK thread pool analogy, If it's something you submit to a thread pool, yes, you can reasonably expect for the responsibility to be on the task to provide useful error messages. But in this case, Liferay itself builds up the task and then says nothing about how it built it, so when the error happens, all you see is an exit code with absolutely no idea what the reasons might be for those exit codes.

However, I can understand wanting to limit the complexity of the class. So what if we were to add the checks and log useful messages to LPKGIndexValidator as is done in this commit, because this is where the problem has the highest visibility?

**Comment by shuyangzhou** [comment]
Processexecutor is just a thin wrapper for Java, if Java does not know how to report a reasonable error message, no way processexecutor can do any better either. And honestly, the exit code is telling you something, that is not zero info, it is just not obvious to everyone.

If you want apply a special error handling to a special usage, that is totally fine. But still it should not make any special assumption that is not globally true.

**Comment by holatuwol** [comment]
@shuyangzhou Got it, I've made it so that it reports what it believes the executable will be, but it does not actually change it.

**Comment by SGM3** [comment]
@holatuwol Shouldn't this be streamlined into a new feature? Not sure about workflow that should be taken here.

In other works, is this LPS appropriate for tracking this?

**Comment by holatuwol** [comment]
@SGM3 Lack of a proper error message is considered a bug, so I think the LPS is still appropriate.

**Comment by SGM3** [comment]
The issue then is a different issue from the original.

Not sure, I think a new LPS should be made?

So we will insert loggin information in LPKGIndexValidator for startup? I felt like the LocalProcessExecutioner would be the appropriate area to add logging.

**Comment by SGM3** [comment]
@holatuwol 
BUMP

**Comment by holatuwol** [comment]
It's still the same problem, but rather than fixing it we've decided that we'll just add better logging, but since we keep closing it, it's better to just create a new LPS. I'll send that along when I find some free time.

**Pull request closed without merging**
